### ISSUE TITLE
Crashes on clicking register on Desire Z

### ISSUE THREAD

**Issue by gjedeer** [Astonex/Antox#657]
Latest build from today.

```
build.board: vision
build.bootloader: 0.84.2000
build.brand: htc_wwe
build.cpu_abi: armeabi-v7a
build.cpu_abi2: armeabi
build.device: vision
build.display: GRI40
build.fingerprint: htc_wwe/htc_vision/vision:2.3.3/GRI40/84109:user/release-keys
build.hardware: vision
build.host: AA137
build.id: GRI40
build.manufacturer: HTC
build.model: HTC Vision
build.product: htc_vision
build.radio: unknown
build.serial: MB139RT01186
build.tags: release-keys
build.time: 1308314475000
build.type: user
build.user: unknown
version.codename: REL
version.incremental: 84109
version.release: 2.3.3
version.sdk_int: 10

11-06 12:15:27.330 I/ActivityManager(1334): Starting activity: Intent { act=android.intent.action.VIEW dat=file:///mnt/sdcard/andsync/antox.apk typ=application/vnd.android.package-archive cmp=android/com.android.internal.app.ResolverActivity } from pid 7076
11-06 12:15:28.570 I/ActivityManager(1334): Starting activity: Intent { act=android.intent.action.VIEW dat=file:///mnt/sdcard/andsync/antox.apk typ=application/vnd.android.package-archive flg=0x3800000 cmp=com.android.packageinstaller/.PackageInstallerActivity } from pid 1334
11-06 12:15:31.260 I/ActivityManager(1334): Starting activity: Intent { dat=file:///mnt/sdcard/andsync/antox.apk cmp=com.android.packageinstaller/.InstallAppProgress (has extras) } from pid 7109
11-06 12:15:31.510 W/PackageManager(1334): grantUriPermission URI=file:///mnt/sdcard/andsync/antox.apk
11-06 12:15:39.030 I/PackageManager(1334): Unpacking native libraries for /data/app/im.tox.antox-1.apk
11-06 12:15:45.090 W/PackageManager(1334): Unknown permission android.permission.READ_EXTERNAL_STORAGE in package im.tox.antox
11-06 12:15:50.540 I/ActivityManager(1334): Starting activity: Intent { act=android.intent.action.MAIN flg=0x10000000 cmp=im.tox.antox/.activities.LoginActivity } from pid 7109
11-06 12:15:51.000 I/ActivityManager(1334): Start proc im.tox.antox for activity im.tox.antox/.activities.LoginActivity: pid=7219 uid=10223 gids={3003, 1015, 1006}
11-06 12:16:00.250 W/ActivityManager(1334): Activity pause timeout for HistoryRecord{405ac928 im.tox.antox/.activities.LoginActivity}
11-06 12:16:01.270 W/ActivityManager(1334): Activity idle timeout for HistoryRecord{405ac928 im.tox.antox/.activities.LoginActivity}
11-06 12:16:01.920 I/ActivityManager(1334): Starting activity: Intent { cmp=im.tox.antox/.activities.CreateAcccountActivity } from pid 7219
11-06 12:16:42.910 I/ActivityManager(1334): Starting activity: Intent { cmp=im.tox.antox/.activities.MainActivity } from pid 7219
11-06 12:16:43.600 E/AndroidRuntime(7219): java.lang.NoSuchMethodError: im.tox.antox.activities.MainActivity.getActionBar
11-06 12:16:43.600 E/AndroidRuntime(7219): 	at im.tox.antox.fragments.LeftPaneFragment.onCreateView(LeftPaneFragment.scala:37)
11-06 12:16:43.600 E/AndroidRuntime(7219): 	at im.tox.antox.activities.MainActivity.onCreate(MainActivity.scala:116)
11-06 12:16:43.600 W/ActivityManager(1334):   Force finishing activity im.tox.antox/.activities.MainActivity
11-06 12:16:44.100 W/ActivityManager(1334): Activity pause timeout for HistoryRecord{409b9a18 im.tox.antox/.activities.MainActivity}
11-06 12:16:45.370 I/ActivityManager(1334): Process im.tox.antox (pid 7219) has died.
11-06 12:16:45.370 W/ActivityManager(1334): Scheduling restart of crashed service im.tox.antox/.tox.ToxDoService in 5000ms
11-06 12:16:45.370 I/WindowManager(1334): WIN DEATH: Window{40cd5070 im.tox.antox/im.tox.antox.activities.CreateAcccountActivity paused=false}
11-06 12:16:50.380 I/ActivityManager(1334): Start proc im.tox.antox for service im.tox.antox/.tox.ToxDoService: pid=7508 uid=10223 gids={3003, 1015, 1006}
11-06 12:16:51.510 I/ActivityManager(1334): Starting activity: Intent { act=android.intent.action.MAIN cat=[android.intent.category.LAUNCHER] flg=0x10200000 cmp=im.tox.antox/.activities.LoginActivity } from pid 1454
11-06 12:16:53.130 I/ActivityManager(1334): Starting activity: Intent { cmp=im.tox.antox/.activities.MainActivity } from pid 7508
11-06 12:16:53.180 E/AndroidRuntime(7508): java.lang.NoSuchMethodError: im.tox.antox.activities.MainActivity.getActionBar
11-06 12:16:53.180 E/AndroidRuntime(7508): 	at im.tox.antox.fragments.LeftPaneFragment.onCreateView(LeftPaneFragment.scala:37)
11-06 12:16:53.180 E/AndroidRuntime(7508): 	at im.tox.antox.activities.MainActivity.onCreate(MainActivity.scala:116)
11-06 12:16:53.190 W/ActivityManager(1334):   Force finishing activity im.tox.antox/.activities.MainActivity
11-06 12:16:53.690 W/ActivityManager(1334): Activity pause timeout for HistoryRecord{40a19f60 im.tox.antox/.activities.MainActivity}
11-06 12:16:54.480 W/ActivityManager(1334): Activity destroy timeout for HistoryRecord{40a77d50 im.tox.antox/.activities.CreateAcccountActivity}
11-06 12:16:54.480 W/ActivityManager(1334): Activity destroy timeout for HistoryRecord{409b9a18 im.tox.antox/.activities.MainActivity}
11-06 12:16:54.720 I/ActivityManager(1334): Process im.tox.antox (pid 7508) has died.
11-06 12:16:54.720 W/ActivityManager(1334): Service crashed 2 times, stopping: ServiceRecord{40d7a3d8 im.tox.antox/.tox.ToxDoService}
11-06 12:16:55.580 I/ActivityManager(1334): Starting activity: Intent { act=android.intent.action.MAIN cat=[android.intent.category.LAUNCHER] flg=0x10200000 cmp=im.tox.antox/.activities.LoginActivity } from pid 1454
11-06 12:16:55.620 I/ActivityManager(1334): Start proc im.tox.antox for activity im.tox.antox/.activities.LoginActivity: pid=7525 uid=10223 gids={3003, 1015, 1006}
11-06 12:16:57.030 I/ActivityManager(1334): Starting activity: Intent { cmp=im.tox.antox/.activities.MainActivity } from pid 7525
11-06 12:16:57.440 E/AndroidRuntime(7525): java.lang.NoSuchMethodError: im.tox.antox.activities.MainActivity.getActionBar
11-06 12:16:57.440 E/AndroidRuntime(7525): 	at im.tox.antox.fragments.LeftPaneFragment.onCreateView(LeftPaneFragment.scala:37)
11-06 12:16:57.440 E/AndroidRuntime(7525): 	at im.tox.antox.activities.MainActivity.onCreate(MainActivity.scala:116)
11-06 12:16:57.450 W/ActivityManager(1334):   Force finishing activity im.tox.antox/.activities.MainActivity
11-06 12:16:57.950 W/ActivityManager(1334): Activity pause timeout for HistoryRecord{40d9a430 im.tox.antox/.activities.MainActivity}
11-06 12:16:58.810 I/ActivityManager(1334): Process im.tox.antox (pid 7525) has died.
11-06 12:16:58.820 W/ActivityManager(1334): Scheduling restart of crashed service im.tox.antox/.tox.ToxDoService in 5000ms
11-06 12:17:03.820 I/ActivityManager(1334): Start proc im.tox.antox for service im.tox.antox/.tox.ToxDoService: pid=7565 uid=10223 gids={3003, 1015, 1006}
11-06 12:17:03.930 W/ActivityManager(1334): Activity destroy timeout for HistoryRecord{409f89c0 im.tox.antox/.activities.LoginActivity}
11-06 12:17:03.930 W/ActivityManager(1334): Activity destroy timeout for HistoryRecord{40a19f60 im.tox.antox/.activities.MainActivity}
11-06 12:17:04.290 I/ActivityManager(1334): Starting activity: Intent { act=de.defim.apk.lightningwall.action.INSTALL dat=specialtastylwnote://noteId/im.tox.antox flg=0x14000000 cmp=de.defim.apk.lightningwall/.Main bnds=[0,595][480,691] (has extras) } from pid -1
11-06 12:17:08.170 W/ActivityManager(1334): Activity destroy timeout for HistoryRecord{40dedf18 im.tox.antox/.activities.LoginActivity}
11-06 12:17:08.170 W/ActivityManager(1334): Activity destroy timeout for HistoryRecord{40d9a430 im.tox.antox/.activities.MainActivity}
11-06 12:17:24.820 I/ActivityManager(1334): Starting activity: Intent { act=android.intent.action.MAIN cat=[android.intent.category.LAUNCHER] flg=0x10100000 cmp=im.tox.antox/.activities.LoginActivity } from pid 1410
11-06 12:17:24.850 V/HtcAppUsageStats(1334): (launch app, package): (Antox, im.tox.antox)
11-06 12:17:27.430 D/Database(7565): dbopen(): path = /data/data/im.tox.antox/databases/userdb, flag = 6
11-06 12:17:27.430 D/Database(7565): dbopen(): path = /data/data/im.tox.antox/databases/userdb, free size = 311
11-06 12:17:27.440 I/ActivityManager(1334): Starting activity: Intent { cmp=im.tox.antox/.activities.MainActivity } from pid 7565
11-06 12:17:27.500 I/dalvikvm(7565): Could not find method im.tox.antox.activities.MainActivity.getActionBar, referenced from method im.tox.antox.fragments.LeftPaneFragment.onCreateView
11-06 12:17:27.500 W/dalvikvm(7565): VFY: unable to resolve virtual method 6288: Lim/tox/antox/activities/MainActivity;.getActionBar ()Landroid/app/ActionBar;
11-06 12:17:27.500 D/dalvikvm(7565): VFY: dead code 0x0009-0058 in Lim/tox/antox/fragments/LeftPaneFragment;.onCreateView (Landroid/view/LayoutInflater;Landroid/view/ViewGroup;Landroid/os/Bundle;)Landroid/view/View;
11-06 12:17:27.510 E/AndroidRuntime(7565): java.lang.NoSuchMethodError: im.tox.antox.activities.MainActivity.getActionBar
11-06 12:17:27.510 E/AndroidRuntime(7565): 	at im.tox.antox.fragments.LeftPaneFragment.onCreateView(LeftPaneFragment.scala:37)
11-06 12:17:27.510 E/AndroidRuntime(7565): 	at im.tox.antox.activities.MainActivity.onCreate(MainActivity.scala:116)
11-06 12:17:27.520 W/ActivityManager(1334):   Force finishing activity im.tox.antox/.activities.MainActivity
11-06 12:17:28.020 W/ActivityManager(1334): Activity pause timeout for HistoryRecord{40b14830 im.tox.antox/.activities.MainActivity}
11-06 12:17:28.860 I/ActivityManager(1334): Process im.tox.antox (pid 7565) has died.
11-06 12:17:28.860 W/ActivityManager(1334): Service crashed 2 times, stopping: ServiceRecord{40b999b8 im.tox.antox/.tox.ToxDoService}
11-06 12:17:38.060 W/ActivityManager(1334): Activity destroy timeout for HistoryRecord{40803fb8 im.tox.antox/.activities.LoginActivity}
11-06 12:17:38.060 W/ActivityManager(1334): Activity destroy timeout for HistoryRecord{40b14830 im.tox.antox/.activities.MainActivity}
```

**Comment by gjedeer** [comment]
Is it fixed?

**Comment by Astonex** [comment]
A lot of things have changed since this issue was made. You should try again using the latest version from F-Droid, or get Antox on Google Play by following the instructions here https://plus.google.com/communities/103125800027884896310

**Comment by gjedeer** [comment]
It works now - the new Antox is awesome, thanks!
